DROP DATABASE IF EXISTS dogs_db;
CREATE DATABASE dogs_db;

USE dogs_db;

CREATE TABLE IF NOT EXISTS dogs (
id INT AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
age INT NOT NULL,
breed VARCHAR(45) NOT NULL,
owner_name VARCHAR(45) NOT NULL,
PRIMARY KEY (id)
);


